### ISSUE TITLE
TorturedArtist関連の修正提案

### ISSUE THREAD

**Issue by BlueScreen000** [Ludeon/RimWorld-ja#22]
翻訳お疲れさまです。
①RimWorld-ja/Core/DefInjected/TraitDef/Traits_Singular.xmlの147行目の“阻害”は“疎外”ではないでしょうか。
②同145行目、149行目においてTorturedArtistは“歪んだ芸術家”と訳す方針であることが伺えますが、“苦しむ芸術家”あるいは“悩める～”、“苦悩する～”といった表現にするほうがより適切ではないでしょうか。対応する日本語の固有の表現が存在しないらしくいまいち怪しい出典しか用意できないのが心苦しいですが、英辞郎on the WEB及び英語版Wikipediaを踏まえると直訳するにしても意訳するにしてもこれらが自然であるように思われます。
以上2件についてご検討いただけますと幸いです。

**Comment by mononok** [comment]
ご指摘ありがとうございます。検討させていただきます。
