### ISSUE TITLE
訳「輸送ポッド落下」についての提案

### ISSUE THREAD

**Issue by BlueScreen000** [Ludeon/RimWorld-ja#28]
RimWorld-ja/Core/DefInjected/IncidentDef/Incidents_Map_Misc.xml　の60-64行目を参照すると、transport pod crash（怪我を負って意識不明の人が落ちてくる）とresource pod crash（物資が落ちてくる）の二つの異なる偶発事件に対して同一の訳「輸送ポッド落下」が当てられているようですが、これらを区別できるような訳に差し替えることを提案します。
差し替え例としては、
transport pod crash……「輸送ポッド落下（人）」「ヒト輸送ポッド落下」「旅客輸送ポッド落下」
resource pod crash……「輸送ポッド落下（物資）」「資源輸送ポッド落下」「貨物輸送ポッド落下」「貨物ポッド落下」
といったものが考えられます（あくまで一例ですので、適当にお洒落でわかりやすいものを考えていただけると嬉しいです）。
特にシナリオエディターや開発者モードによって事件を起こしたり禁止したりしたいとき、両者の見分けがつきやすいと便利になると思われます。ご検討のほうよろしくお願いいたします。

**Comment by NM-Grack** [comment]
ありがとうございます。
transport pod crashについて:
この単語ははほかの場所でも使われており、そちらの方では「輸送ポッド事故」と翻訳されているため、Incidents_Map_Mics.xmlの方もそれに合わせて「輸送ポッド事故」と変更いたします。
（また、transportには軍事的な意味合いを除いて「人」という意味は含まれてない印象なので、翻訳にも人というニュアンスは含めない方が良いかと感じました）
resource pod crashについて：
単語に輸送という意味は含まれていなさそうなので、輸送ポッドではなく資源ポッドと翻訳した方がより適切ですね。
こちらの方はtransport pod crashの変更点と合わせて「資源ポッド事故」に変更いたします。
