### ISSUE TITLE
mechanitor の訳語について

### ISSUE THREAD

**Issue by kankoromochi** [Ludeon/RimWorld-ja#58]
「mechanitor」についてですが、従来「Mechanite:メカナイト」が存在していたことを考えると、「メカニター」ではなく「メカナイター」とするのが適切だと思いますがいかがでしょうか。語感的にもしっくりきますし…

まずは皆さん遊びたいでしょうから、固有名詞は今後すり合わせるとして全体的にはとりあえず翻訳を急いでおりますが、出現頻度が高いので先に議題にあげさせていただきました。

とりあえず私が担当したところはメカナイターとしてありますが、反対意見の方が多ければすぐ修正いたします。
よろしくお願いいたします。

**Comment by NM-Grack** [comment]
メカナイトとメカナイターについては気づきませんでした。
自分はメカニックが元の造語だと思ったのでメカニターと訳したんですよね。
そこで思ったのですが、メカナイトは細菌性の機械を指す言葉ですし、mechanitorの実態に合わせて下記のようにするのはどうでしょうか？

・mechanitorが人物を指す言葉ならメカニター
・mechanitorが機械、もしくはその他を指す言葉ならメカナイター

私はまだゼノエディターから先に進んでないのでmecanitorがどういう存在なのか把握していません。
そちらはどうでしょうか？
(一応、シナリオ選択の文章的には人物を指す言葉のような気はします)

**Comment by kankoromochi** [comment]
コメントありがとうございます。
今日一日考えていたのですが、～nitor、で終わる英語の単語はほとんど～ニター、の単語なので、やはりメカニターが適切か、と思い直しました。
自己解決で恐縮ですが、メカニターとして修正を入れておきます。

**Comment by NM-Grack** [comment]
わかりました。
今後メカニターと訳します。
