### ISSUE TITLE
修正提案

### ISSUE THREAD

**Issue by 69495** [Ludeon/RimWorld-ja#7]
https://github.com/mononok/RimWorld-Ja-sandbox/blob/fbf559e3005c71df827d4f848d7a0d13c3be1128/Keyed/Misc_Gameplay.xml
の140行目の
<FermentationProgress>発行中: {0} (残り{1})</FermentationProgress>
は
<FermentationProgress>発酵中: {0} (残り{1})</FermentationProgress>
ではないでしょうか？

**Comment by mononok** [comment]
指摘ありがとうございました。
