### ISSUE TITLE
yttakinの訳について

### ISSUE THREAD

**Issue by tiorip** [Ludeon/RimWorld-ja#73]
https://store.steampowered.com/news/app/294100/view/3319740412995643281
発音への言及がある造語という点を考慮してイータキーンとする提案を行います
翻訳済部分への影響は現時点で

> Biotech\DefInjected\ThingDef\Apparel_Various.xml
> Biotech\DefInjected\XenotypeDef\XenotypeDefs.xml

の数か所にとどまるようです

**Comment by NM-Grack** [comment]
ありがとうございます。
"pronounced roughly as ee-ta-keen"という部分ですね、見逃していました。
ただ、NewRatkinPlusというMODがあるのですが、そちらに登場するRatkinという種族名がラットキンと翻訳され、広く認知されています。
この-kinの部分はそれに倣い-キンと翻訳したいと思っています。
yttaの部分に関しましてはおっしゃる通りイータの方がよさそうですね。

yttakinはイータキンと変更いたします。
反映はもうしばらく後になりますので、それまでお待ちください。
