### ISSUE TITLE
「潰れた～」について

### ISSUE THREAD

**Issue by 747** [Ludeon/RimWorld-ja#8]
翻訳お疲れさまです。

Buildings_Natural.xml にある "Compacted" の訳で「潰れた」となっている行ですが、これは本来「一つの場所に押し固められた」というような意味なので、「凝集したプラスチール」とか「集積したプラスチール」とか、あるいは平たくするなら「プラスチール溜まり」などの方がいいと思います。

今までずっとこの訳なので何とも今更ですが、1.0を機に検討するのもいいのではないかと思っています。

なお、
```
<MineableSteel.label>潰れた鉄材</MineableSteel.label>
<MineableSteel.description>古代の崩落した遺跡の残り,鉄を豊富に含んでいます.</MineableSteel.description>
```
は、
- 鉄材→（鋼材／スチール）
- 鉄を豊富に→スチールを豊富

が正しいと思います。

**Comment by mononok** [comment]
ありがとうございます。参考にさせてもらいました。
